[package]
name = "auth"
version = "0.1.0"
edition = "2024"

[lib]
name = "auth_seed" 
path = "src/lib.rs"

[dependencies]
tokio = { workspace = true }
axum = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
dotenvy = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
jsonwebtoken = { workspace = true }
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true }
argon2 = { version = "0.5", features = ["std"] }
diesel = { version = "2.3.3", features = ["postgres", "r2d2", "uuid", "chrono"] }
# diesel-derive-enum = "2.1"

# Reference local workspace crates
common = { path = "../../libs/common" }
utils = { path = "../../libs/utils" }
services = { path = "../../libs/services" }
