mod handlers;
mod repository;
mod service;
pub mod schema; // generated by diesel print-schema

use axum::{Router, routing::{get, post}};
use diesel::r2d2::{ConnectionManager, Pool};
use diesel::PgConnection;
use std::sync::Arc;
use dotenvy::dotenv;
use tracing_subscriber::{layer::SubscriberExt, util::SubscriberInitExt};

use repository::DriverRepository;
use service::DriverService;

#[derive(Clone)]
pub struct AppState {
    pub driver_service: Arc<DriverService>,
}

#[tokio::main]
async fn main() -> Result<(), anyhow::Error> {
    dotenv().ok();

    tracing_subscriber::registry()
        .with(tracing_subscriber::fmt::layer())
        .init();

    let database_url = std::env::var("DATABASE_URL")
        .expect("DATABASE_URL must be set");

    let manager = ConnectionManager::<PgConnection>::new(database_url);
    let pool = Pool::builder().build(manager)?;

    let repo = DriverRepository::new(pool);
    let service = Arc::new(DriverService::new(repo));
    let state = AppState { driver_service: service };

    let app = Router::new()
        .route("/health", get(handlers::health_check))
        .route("/api/drivers", get(handlers::list_drivers).post(handlers::create_driver))
        .route("/api/drivers/:id", get(handlers::get_driver))
        .with_state(state);

    let addr = "0.0.0.0:8001";
    tracing::info!("🚗 Driver service listening on {}", addr);

    axum::serve(tokio::net::TcpListener::bind(addr).await?, app).await?;
    Ok(())
}
