[package]
name = "services"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
resend-rs = "0.19.0"
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true }
uuid = { workspace = true }
sha1 = { workspace = true }
chrono = { workspace = true }

common = { path = "../common" }
hex = "0.4"
serde_json = "1.0"
redis = { version = "0.29.1", features = ["tokio-comp", "connection-manager"] }
futures-util = "0.3"