[package]
name = "admin"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
axum = { workspace = true }
uuid = { workspace = true }
dotenvy = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bigdecimal = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true }
diesel = { version = "2.3.3", features = ["postgres", "r2d2", "uuid", "chrono", "numeric"] }
diesel-derive-enum = { version = "2.1", features = ["postgres"] }

common = { path = "../../libs/common" }
